models:
  - name: employees_stg
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: advancerequestrequiresapproval
        data_type: BOOLEAN
      - name: clientid
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: employee_createdat_local
        data_type: TIMESTAMP
      - name: employee_deletedat_local
        data_type: TIMESTAMP
      - name: employeeid
        data_type: TEXT
      - name: employee_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: employee_mobile
        data_type: TEXT
      - name: employee_salarytype
        data_type: TEXT
      - name: employee_status
        data_type: TEXT
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: hash_column
        data_type: TEXT
      - name: iseligibleforadvancerequest
        data_type: BOOLEAN
      - name: iseligibleforclaimrequest
        data_type: BOOLEAN
      - name: loaddate
        data_type: TIMESTAMP
      - name: operation
        data_type: TEXT
      - name: tookfirstsalary
        data_type: BOOLEAN

  - name: employees_stg_new
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: advancerequestrequiresapproval
        data_type: BOOLEAN
      - name: clientid
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: employee_createdat_local
        data_type: TIMESTAMP
      - name: employee_deletedat_local
        data_type: TIMESTAMP
      - name: employeeid
        data_type: TEXT
      - name: employee_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: employee_mobile
        data_type: TEXT
      - name: employee_salarytype
        data_type: TEXT
      - name: employee_status
        data_type: TEXT
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: hash_column
        data_type: TEXT
      - name: iseligibleforadvancerequest
        data_type: BOOLEAN
      - name: iseligibleforclaimrequest
        data_type: BOOLEAN
      - name: loaddate
        data_type: TIMESTAMP
      - name: operation
        data_type: TEXT
      - name: tookfirstsalary
        data_type: BOOLEAN

  - name: employees_stg_update
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: advancerequestrequiresapproval
        data_type: BOOLEAN
      - name: clientid
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: employee_createdat_local
        data_type: TIMESTAMP
      - name: employee_deletedat_local
        data_type: TIMESTAMP
      - name: employeeid
        data_type: TEXT
      - name: employee_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: employee_mobile
        data_type: TEXT
      - name: employee_salarytype
        data_type: TEXT
      - name: employee_status
        data_type: TEXT
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: hash_column
        data_type: TEXT
      - name: iseligibleforadvancerequest
        data_type: BOOLEAN
      - name: iseligibleforclaimrequest
        data_type: BOOLEAN
      - name: loaddate
        data_type: TIMESTAMP
      - name: operation
        data_type: TEXT
      - name: tookfirstsalary
        data_type: BOOLEAN

  - name: employees_stg_exp
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: advancerequestrequiresapproval
        data_type: BOOLEAN
      - name: clientid
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: employee_createdat_local
        data_type: TIMESTAMP
      - name: employee_deletedat_local
        data_type: TIMESTAMP
      - name: employeeid
        data_type: TEXT
      - name: employee_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: employee_mobile
        data_type: TEXT
      - name: employee_salarytype
        data_type: TEXT
      - name: employee_status
        data_type: TEXT
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: hash_column
        data_type: TEXT
      - name: iseligibleforadvancerequest
        data_type: BOOLEAN
      - name: iseligibleforclaimrequest
        data_type: BOOLEAN
      - name: loaddate
        data_type: TIMESTAMP
      - name: operation
        data_type: TEXT
      - name: tookfirstsalary
        data_type: BOOLEAN

  - name: employees_dimension
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: advancerequestrequiresapproval
        data_type: BOOLEAN
      - name: clientid
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: employee_createdat_local
        data_type: TIMESTAMP
      - name: employee_deletedat_local
        data_type: TIMESTAMP
      - name: employeeid
        data_type: TEXT
      - name: employee_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: employee_mobile
        data_type: TEXT
      - name: employee_salarytype
        data_type: TEXT
      - name: employee_status
        data_type: TEXT
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: hash_column
        data_type: TEXT
      - name: iseligibleforadvancerequest
        data_type: BOOLEAN
      - name: iseligibleforclaimrequest
        data_type: BOOLEAN
      - name: loaddate
        data_type: TIMESTAMP
      - name: operation
        data_type: TEXT
      - name: tookfirstsalary
        data_type: BOOLEAN
          
  - name: clients_stg
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: operation
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: clientid
        data_type: TEXT
      - name: hash_column
        data_type: TEXT
      - name: loaddate
        data_type: TIMESTAMP
      - name: address_city
        data_type: TEXT
      - name: address_governorate
        data_type: TEXT
      - name: client_createdat_local
        data_type: TIMESTAMP
      - name: client_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: client_status
        data_type: TEXT
      - name: clientname_en
        data_type: TEXT
      - name: clienttype
        data_type: TEXT
      - name: industrytype
        data_type: TEXT
      - name: numofemployees
        data_type: FLOAT
      - name: salaryadvanceaccesslevel
        data_type: TEXT

  - name: clients_stg_new
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: operation
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: clientid
        data_type: TEXT
      - name: hash_column
        data_type: TEXT
      - name: loaddate
        data_type: TIMESTAMP
      - name: address_city
        data_type: TEXT
      - name: address_governorate
        data_type: TEXT
      - name: client_createdat_local
        data_type: TIMESTAMP
      - name: client_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: client_status
        data_type: TEXT
      - name: clientname_en
        data_type: TEXT
      - name: clienttype
        data_type: TEXT
      - name: industrytype
        data_type: TEXT
      - name: numofemployees
        data_type: FLOAT
      - name: salaryadvanceaccesslevel
        data_type: TEXT

  - name: clients_stg_update
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: operation
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: clientid
        data_type: TEXT
      - name: hash_column
        data_type: TEXT
      - name: loaddate
        data_type: TIMESTAMP
      - name: address_city
        data_type: TEXT
      - name: address_governorate
        data_type: TEXT
      - name: client_createdat_local
        data_type: TIMESTAMP
      - name: client_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: client_status
        data_type: TEXT
      - name: clientname_en
        data_type: TEXT
      - name: clienttype
        data_type: TEXT
      - name: industrytype
        data_type: TEXT
      - name: numofemployees
        data_type: FLOAT
      - name: salaryadvanceaccesslevel
        data_type: TEXT

  - name: clients_stg_exp
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: operation
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: clientid
        data_type: TEXT
      - name: hash_column
        data_type: TEXT
      - name: loaddate
        data_type: TIMESTAMP
      - name: address_city
        data_type: TEXT
      - name: address_governorate
        data_type: TEXT
      - name: client_createdat_local
        data_type: TIMESTAMP
      - name: client_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: client_status
        data_type: TEXT
      - name: clientname_en
        data_type: TEXT
      - name: clienttype
        data_type: TEXT
      - name: industrytype
        data_type: TEXT
      - name: numofemployees
        data_type: FLOAT
      - name: salaryadvanceaccesslevel
        data_type: TEXT

  - name: clients_dimension
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: text
        constraints:
          - type: not_null
          - type: primary_key
      - name: operation
        data_type: TEXT
      - name: currentflag
        data_type: BOOLEAN
      - name: expdate
        data_type: TIMESTAMPTZ
      - name: clientid
        data_type: TEXT
      - name: hash_column
        data_type: TEXT
      - name: loaddate
        data_type: TIMESTAMP
      - name: address_city
        data_type: TEXT
      - name: address_governorate
        data_type: TEXT
      - name: client_createdat_local
        data_type: TIMESTAMP
      - name: client_modifiedat_local
        data_type: TIMESTAMP
      - name: utc
        data_type: int
      - name: client_status
        data_type: TEXT
      - name: clientname_en
        data_type: TEXT
      - name: clienttype
        data_type: TEXT
      - name: industrytype
        data_type: TEXT
      - name: numofemployees
        data_type: FLOAT
      - name: salaryadvanceaccesslevel
        data_type: TEXT
